application: earthquakeui
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: earthquake_server.app

libraries:
- name: MySQLdb
  version: "latest"

- name: jinja2
  version: "latest"
